In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("IRIS.csv")
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [6]:
df.describe()


,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [7]:
df.isnull()

,sepal_length,sepal_width,petal_length,petal_width,species
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
145,False,False,False,False,False
146,False,False,False,False,False
147,False,False,False,False,False
148,False,False,False,False,False


In [8]:
df.value_counts()

sepal_length  sepal_width  petal_length  petal_width  species       
4.9           3.1          1.5           0.1          Iris-setosa       3
5.8           2.7          5.1           1.9          Iris-virginica    2
5.1           3.5          1.4           0.2          Iris-setosa       1
4.9           3.0          1.4           0.2          Iris-setosa       1
4.7           3.2          1.3           0.2          Iris-setosa       1
                                                                       ..
6.7           3.0          5.2           2.3          Iris-virginica    1
6.3           2.5          5.0           1.9          Iris-virginica    1
6.5           3.0          5.2           2.0          Iris-virginica    1
6.2           3.4          5.4           2.3          Iris-virginica    1
5.9           3.0          5.1           1.8          Iris-virginica    1
Name: count, Length: 147, dtype: int64

In [11]:
# convert 3 species into 1,2,3 numerical format

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

df.sample(10)

,sepal_length,sepal_width,petal_length,petal_width,species
21,5.1,3.7,1.5,0.4,0
141,6.9,3.1,5.1,2.3,2
112,6.8,3.0,5.5,2.1,2
107,7.3,2.9,6.3,1.8,2
123,6.3,2.7,4.9,1.8,2
68,6.2,2.2,4.5,1.5,1
45,4.8,3.0,1.4,0.3,0
88,5.6,3.0,4.1,1.3,1
108,6.7,2.5,5.8,1.8,2
78,6.0,2.9,4.5,1.5,1


In [12]:
#Train Test Split
from sklearn.model_selection import train_test_split

x = df.drop(["species"], axis=1)
y = df["species"]

x_train, x_test, y_train, y_yest = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [13]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=100)
lr.fit(x_train, y_train)

LogisticRegression()

In [14]:
# KNN

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [15]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [20]:
#Predict

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

models = {'LogisticRegression': lr, 'KNeighborsClassifier': knn, 'GaussianNB': nb}

for name, model in models.items():
    y_pred = model.predict(x)
    print(f"\n{name}:")

    print("Accuracy :",accuracy_score(y,y_pred))

    print("Confusion Matrix:", confusion_matrix(y,y_pred))

    print("Classification Report:",classification_report(y,y_pred))


LogisticRegression:
Accuracy : 0.98
Confusion Matrix: [[50  0  0]
 [ 0 47  3]
 [ 0  0 50]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.94      0.97        50
           2       0.94      1.00      0.97        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150


KNeighborsClassifier:
Accuracy : 0.9733333333333334
Confusion Matrix: [[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      0.94      0.96        50
           2       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97    